FROM mcr.microsoft.com/dotnet/sdk:9.0 AS serverbuild

WORKDIR /app

COPY /mPhotos-svelte.Server/*.csproj ./
RUN dotnet restore --disable-parallel

COPY /mPhotos-svelte.Server .
RUN dotnet publish -c Release -o out --disable-parallel

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime

WORKDIR /app
COPY --from=serverbuild /app/out ./

EXPOSE 7217
ENV ASPNETCORE_URLS=https://*:7217

ENTRYPOINT ["dotnet", "/app/mPhotos-svelte.Server.dll"]